### ISSUE TITLE
As a user, I want to have enemies generated

### ISSUE THREAD

**Issue by BinaryTiger** [vinleclair/infinite-coast#2]
**CoS**
 - [x] Encounter level is set by an option flag with a sensible default (`executable --lvl=2`)
 - [x] Choosing an encounter from a list of 4 different ones for this version is acceptable (all for level 1)
    - [x] Encounter list is predetermined and in a configuration file (format could be json or yaml or someting else)
    - [x] Encounter is chosen randomly
 - [x] Enemies from the chosen encounter are place "smartly" on their side of the board (top half, or left half, etc)

**Notes**
Example encounter list, yaml:
```yaml
- encounter:
    level: 1
    enemies:
      - goblin:
          hp: 14
      - goblin:
          hp: 13
      - goblin:
          hp: 14
```

**DoD**
The executable return a string representing the arena with placed enemies.
E.G:
0 as empty space, X as hazards and E as enemies on a 4x4 grid
```
[
  0 0 E 0
  0 E X 0
  0 0 X 0
  0 0 X X
]
