### ISSUE TITLE
As as user, I want merchants table generated

### ISSUE THREAD

**Issue by BinaryTiger** [vinleclair/infinite-coast#5]
**Cos**
 - [x] Merchant available items are in function of the players levels
 - [x] Merchant available coins to buy items from the player is also in function of the players level
 - [x] A command is available to generate only a merchant (E.G `executable generate merchant --lvl=3`
 - [x] Available items are configured in an editable configuration file just like enemies and encounter

**Notes**
-  Should be able to support new options in the future like `maxAvailableCoins`, types [Rich, Poor, Normal], etc

**DoD**
A merchant table with items appropriate for the players level is generated in a plain text format, preferably a standard format like `json` or `yaml`

E.G:
```yaml
name: Archimed
coins: 15000
inventory:
  - item: potion of health
    price: 15
  - item: sword of vengeance +1
    price: 1600
```
